### ISSUE TITLE
Improve error handling `race_ok` variants

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/futures-concurrency#98]
We should duplicate the pretty printing logic of https://github.com/yoshuawuyts/futures-concurrency/pull/94 for the remainder of the `race_ok` types.

## Tasks
- [x] `impl RaceOk for Vec`
- [X] `impl RaceOk for array`
- [x] `impl RaceOk for tuple`

**Comment by poliorcetics** [comment]
Wasn't this fixed in the last release ?
